'use client';

import { useState, useEffect, useRef } from 'react';
import { Upload, FileText, Calendar, ChevronRight } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

export default function ResumesPage() {
  const [masterResume, setMasterResume] = useState('');
  const [tailoredResumes, setTailoredResumes] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [activeResume, setActiveResume] = useState<'master' | string>('master');
  const [viewMode, setViewMode] = useState<'visual' | 'raw'>('visual');
  
  const fileInputRef = useRef<HTMLInputElement>(null);

  const fetchResumes = () => {
    fetch('/api/resumes')
      .then(res => res.json())
      .then(data => {
        setMasterResume(data.master);
        setTailoredResumes(data.tailored);
        setLoading(false);
      });
  };

  useEffect(() => {
    fetchResumes();
  }, []);

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setUploading(true);
    try {
      const formData = new FormData();
      formData.append('file', file);

      const res = await fetch('/api/resumes', {
        method: 'POST',
        body: formData
      });

      if (!res.ok) throw new Error('Upload failed');

      fetchResumes();
      setActiveResume('master');
      alert('Master Resume uploaded successfully!');
    } catch (e) {
      alert('Failed to upload resume.');
    } finally {
      setUploading(false);
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  const getActiveContent = () => {
    if (activeResume === 'master') return masterResume;
    const found = tailoredResumes.find(r => r.id === activeResume);
    return found ? found.content : '';
  };

  if (loading) return <div className="p-8 text-center text-gray-500">Loading resumes...</div>;

  return (
    <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row gap-8">
      {/* Sidebar List */}
      <div className="md:w-1/3 flex-none space-y-6">
        <div>
          <h1 className="text-3xl font-extrabold text-gray-900 mb-2">Resumes</h1>
          <p className="text-gray-500 text-sm">Upload your master resume and review all targeted variations generated by the AI.</p>
        </div>

        <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden mb-6">
          <div className="p-4 bg-gray-50 border-b border-gray-200">
            <h2 className="font-bold text-gray-800 text-sm uppercase tracking-wider">Master Source</h2>
          </div>
          
          <button 
            onClick={() => setActiveResume('master')}
            className={`w-full text-left p-4 flex items-center justify-between border-b border-gray-100 transition-colors ${activeResume === 'master' ? 'bg-blue-50 border-l-4 border-l-blue-600' : 'hover:bg-gray-50 border-l-4 border-l-transparent'}`}
          >
            <div className="flex items-center gap-3">
              <div className="bg-blue-100 text-blue-600 p-2 rounded-lg">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <div className="font-bold text-gray-900">Master Resume</div>
                <div className="text-xs text-gray-500">Used as base for tailoring</div>
              </div>
            </div>
            {activeResume === 'master' && <ChevronRight className="w-4 h-4 text-blue-600" />}
          </button>

          <div className="p-4 bg-white">
            <input 
              type="file" 
              accept=".md,.txt,.docx" 
              className="hidden" 
              ref={fileInputRef} 
              onChange={handleFileUpload}
            />
            <button 
              onClick={() => fileInputRef.current?.click()}
              disabled={uploading}
              className="w-full flex flex-col items-center justify-center gap-2 border-2 border-dashed border-gray-300 rounded-lg p-6 hover:border-blue-500 hover:bg-blue-50 transition-all text-gray-500 hover:text-blue-600 group"
            >
              <Upload className="w-6 h-6 group-hover:-translate-y-1 transition-transform" /> 
              <span className="text-sm font-bold">{uploading ? 'Processing File...' : 'Replace Master Resume'}</span>
              <span className="text-xs text-gray-400">Accepts .md, .txt, or .docx</span>
            </button>
          </div>
        </div>

        {tailoredResumes.length > 0 && (
          <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
            <div className="p-4 bg-gray-50 border-b border-gray-200">
              <h2 className="font-bold text-gray-800 text-sm uppercase tracking-wider">Generated Variations</h2>
            </div>
            <div className="max-h-[500px] overflow-y-auto">
              {tailoredResumes.map(resume => (
                <button 
                  key={resume.id}
                  onClick={() => setActiveResume(resume.id)}
                  className={`w-full text-left p-4 flex items-center justify-between border-b border-gray-100 transition-colors ${activeResume === resume.id ? 'bg-blue-50 border-l-4 border-l-blue-600' : 'hover:bg-gray-50 border-l-4 border-l-transparent'}`}
                >
                  <div className="truncate pr-4">
                    <div className="font-bold text-gray-900 text-sm truncate">{resume.name.replace('.md', '')}</div>
                    <div className="text-xs text-gray-500 flex items-center gap-1 mt-1">
                      <Calendar className="w-3 h-3" /> {new Date(resume.createdAt).toLocaleString()}
                    </div>
                  </div>
                  {activeResume === resume.id && <ChevronRight className="w-4 h-4 flex-none text-blue-600" />}
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Main Preview Area */}
      <div className="md:w-2/3 flex-grow">
        <div className="bg-white border border-gray-200 rounded-xl shadow-sm h-[800px] flex flex-col overflow-hidden">
          
          {/* Viewer Header */}
          <div className="p-4 bg-gray-50 border-b border-gray-200 flex justify-between items-center flex-none">
            <h3 className="font-mono text-sm font-bold text-gray-700">
              {activeResume === 'master' ? 'resume.md' : activeResume}
            </h3>
            <div className="flex bg-gray-200 rounded-lg p-1">
              <button 
                onClick={() => setViewMode('visual')} 
                className={`px-3 py-1.5 text-xs font-bold rounded-md transition-colors ${viewMode === 'visual' ? 'bg-white shadow-sm text-blue-600' : 'text-gray-500 hover:text-gray-700'}`}
              >
                Visual Document
              </button>
              <button 
                onClick={() => setViewMode('raw')} 
                className={`px-3 py-1.5 text-xs font-bold rounded-md transition-colors ${viewMode === 'raw' ? 'bg-white shadow-sm text-blue-600' : 'text-gray-500 hover:text-gray-700'}`}
              >
                Raw Markdown
              </button>
            </div>
          </div>

          {/* Viewer Body */}
          <div className={`p-8 overflow-y-auto flex-grow ${viewMode === 'visual' ? 'bg-gray-100' : 'bg-gray-900'}`}>
             {getActiveContent() ? (
               viewMode === 'visual' ? (
                 <div className="bg-white max-w-3xl mx-auto p-12 shadow-md border border-gray-200 min-h-full">
                    <div className="prose prose-sm max-w-none text-gray-800">
                      <ReactMarkdown>
                        {getActiveContent()}
                      </ReactMarkdown>
                    </div>
                 </div>
               ) : (
                 <pre className="text-gray-200 font-mono text-sm leading-loose whitespace-pre-wrap">
                   {getActiveContent()}
                 </pre>
               )
             ) : (
               <div className="h-full flex items-center justify-center text-gray-500 italic">
                 {activeResume === 'master' ? 'No master resume uploaded yet.' : 'Empty file.'}
               </div>
             )}
          </div>

        </div>
      </div>
    </div>
  );
}
