-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS company_directory (
  id         serial PRIMARY KEY,
  name       text NOT NULL,
  slug       text NOT NULL,
  ats        text NOT NULL CHECK (ats IN ('greenhouse', 'ashby', 'lever')),
  careers_url text GENERATED ALWAYS AS (
    CASE ats
      WHEN 'greenhouse' THEN 'https://job-boards.greenhouse.io/' || slug
      WHEN 'ashby'      THEN 'https://jobs.ashbyhq.com/'         || slug
      WHEN 'lever'      THEN 'https://jobs.lever.co/'            || slug
    END
  ) STORED,
  UNIQUE (ats, slug)
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_company_directory_name_trgm
  ON company_directory USING gin (name gin_trgm_ops);

-- ─────────────────────────────────────────────────────────────────────────────
-- GREENHOUSE  (job-boards.greenhouse.io/{slug})
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO company_directory (name, slug, ats) VALUES

('1Password',            'agilebits',          'greenhouse'),
('Abnormal Security',    'abnormalsecurity',    'greenhouse'),
('Acorns',               'acorns',             'greenhouse'),
('Acquia',               'acquia',             'greenhouse'),
('Addepar',              'addepar',            'greenhouse'),
('Adroll',               'adroll',             'greenhouse'),
('Affirm',               'affirm',             'greenhouse'),
('Airtable',             'airtable',           'greenhouse'),
('Algolia',              'algolia',            'greenhouse'),
('Alloy',                'alloy',              'greenhouse'),
('Amplitude',            'amplitude',          'greenhouse'),
('Amperity',             'amperity',           'greenhouse'),
('Anduril',              'anduril',            'greenhouse'),
('Anthropic',            'anthropic',          'greenhouse'),
('Appian',               'appian',             'greenhouse'),
('Appsflyer',            'appsflyer',          'greenhouse'),
('Aqua Security',        'aquasecurity',       'greenhouse'),
('Arcesium',             'arcesium',           'greenhouse'),
('Armis',                'armis',              'greenhouse'),
('Artsy',                'artsy',              'greenhouse'),
('Asana',                'asana',              'greenhouse'),
('AssemblyAI',           'assemblyai',         'greenhouse'),
('Attentive',            'attentive',          'greenhouse'),
('Automox',              'automox',            'greenhouse'),
('Axonius',              'axonius',            'greenhouse'),
('Backblaze',            'backblaze',          'greenhouse'),
('Bandwidth',            'bandwidth',          'greenhouse'),
('Bazaarvoice',          'bazaarvoice',        'greenhouse'),
('Benchling',            'benchling',          'greenhouse'),
('Better.com',           'better',             'greenhouse'),
('Betterment',           'betterment',         'greenhouse'),
('BigCommerce',          'bigcommerce',        'greenhouse'),
('BigPanda',             'bigpanda',           'greenhouse'),
('Bitly',                'bitly',              'greenhouse'),
('Blend',                'blend',              'greenhouse'),
('Blockdaemon',          'blockdaemon',        'greenhouse'),
('Bloomreach',           'bloomreach',         'greenhouse'),
('Bolt',                 'bolt',               'greenhouse'),
('Box',                  'box',                'greenhouse'),
('Braze',                'braze',              'greenhouse'),
('Brex',                 'brex',               'greenhouse'),
('Brightcove',           'brightcove',         'greenhouse'),
('Brilliant',            'brilliant',          'greenhouse'),
('Calendly',             'calendly',           'greenhouse'),
('Cameo',                'cameo',              'greenhouse'),
('Canva',                'canva',              'greenhouse'),
('Carbon',               'carbon',             'greenhouse'),
('Carta',                'carta',              'greenhouse'),
('Cedar',                'cedar',              'greenhouse'),
('Celonis',              'celonis',            'greenhouse'),
('Census',               'census',             'greenhouse'),
('Chargebee',            'chargebee',          'greenhouse'),
('Checkr',               'checkr',             'greenhouse'),
('Chime',                'chime',              'greenhouse'),
('Clari',                'clari',              'greenhouse'),
('Clearbit',             'clearbit',           'greenhouse'),
('Clearcover',           'clearcover',         'greenhouse'),
('ClickUp',              'clickup',            'greenhouse'),
('CloudBees',            'cloudbees',          'greenhouse'),
('Cloudflare',           'cloudflare',         'greenhouse'),
('Cloudinary',           'cloudinary',         'greenhouse'),
('Cockroach Labs',       'cockroachlabs',      'greenhouse'),
('Coda',                 'codahq',             'greenhouse'),
('Code42',               'code42',             'greenhouse'),
('Coinbase',             'coinbase',           'greenhouse'),
('Collibra',             'collibra',           'greenhouse'),
('Confluent',            'confluent',          'greenhouse'),
('Contentful',           'contentful',         'greenhouse'),
('Contentstack',         'contentstack',       'greenhouse'),
('Contrast Security',    'contrastsecurity',   'greenhouse'),
('Corelight',            'corelight',          'greenhouse'),
('Coupang',              'coupang',            'greenhouse'),
('Coursera',             'coursera',           'greenhouse'),
('Cresta',               'cresta',             'greenhouse'),
('Cribl',                'cribl',              'greenhouse'),
('Crossbeam',            'crossbeam',          'greenhouse'),
('Culture Amp',          'cultureamp',         'greenhouse'),
('Dashlane',             'dashlane',           'greenhouse'),
('Databricks',           'databricks',         'greenhouse'),
('Datadog',              'datadoghq',          'greenhouse'),
('Dataiku',              'dataiku',            'greenhouse'),
('DataRobot',            'datarobot',          'greenhouse'),
('DataStax',             'datastax',           'greenhouse'),
('Datavant',             'datavant',           'greenhouse'),
('dbt Labs',             'dbtlabs',            'greenhouse'),
('Deepgram',             'deepgram',           'greenhouse'),
('Degreed',              'degreed',            'greenhouse'),
('Demandbase',           'demandbase',         'greenhouse'),
('Dialpad',              'dialpad',            'greenhouse'),
('Docker',               'docker',             'greenhouse'),
('Domino Data Lab',      'dominodatalab',      'greenhouse'),
('DoorDash',             'doordash',           'greenhouse'),
('Dropbox',              'dropbox',            'greenhouse'),
('DriveWealth',          'drivewealth',        'greenhouse'),
('Duolingo',             'duolingo',           'greenhouse'),
('Easypost',             'easypost',           'greenhouse'),
('Elastic',              'elastic',            'greenhouse'),
('Electric',             'electric',           'greenhouse'),
('ElevenLabs',           'elevenlabs',         'greenhouse'),
('Emotive',              'emotive',            'greenhouse'),
('Envoy',                'envoy',              'greenhouse'),
('Exabeam',              'exabeam',            'greenhouse'),
('Expensify',            'expensify',          'greenhouse'),
('Fastly',               'fastly',             'greenhouse'),
('Fetch Rewards',        'fetchrewards',       'greenhouse'),
('Figma',                'figma',              'greenhouse'),
('Fingerprint',          'fingerprintjs',      'greenhouse'),
('Fivetran',             'fivetran',           'greenhouse'),
('Flatfile',             'flatfile',           'greenhouse'),
('Flexport',             'flexport',           'greenhouse'),
('Forter',               'forter',             'greenhouse'),
('Foursquare',           'foursquare',         'greenhouse'),
('Freshworks',           'freshworks',         'greenhouse'),
('Front',                'front',              'greenhouse'),
('Fullstory',            'fullstory',          'greenhouse'),
('G2',                   'g2',                 'greenhouse'),
('Garner Health',        'garnerhealth',       'greenhouse'),
('GitLab',               'gitlab',             'greenhouse'),
('Glean',                'glean',              'greenhouse'),
('Gong',                 'gong',               'greenhouse'),
('GoodRx',               'goodrx',             'greenhouse'),
('Grafana Labs',         'grafanalabs',        'greenhouse'),
('Guild Education',      'guildeducation',     'greenhouse'),
('Gusto',                'gusto',              'greenhouse'),
('H2O.ai',               'h2oai',              'greenhouse'),
('HackerOne',            'hackerone',          'greenhouse'),
('Harness',              'harness',            'greenhouse'),
('HashiCorp',            'hashicorp',          'greenhouse'),
('Heap',                 'heap',               'greenhouse'),
('Highspot',             'highspot',           'greenhouse'),
('Hightouch',            'hightouch',          'greenhouse'),
('Honeycomb',            'honeycombio',        'greenhouse'),
('Hopper',               'hopper',             'greenhouse'),
('HubSpot',              'hubspot',            'greenhouse'),
('Hugging Face',         'huggingface',        'greenhouse'),
('Human Interest',       'humaninterest',      'greenhouse'),
('Ibotta',               'ibotta',             'greenhouse'),
('Imply',                'imply',              'greenhouse'),
('Instabase',            'instabase',          'greenhouse'),
('Instacart',            'instacart',          'greenhouse'),
('Intercom',             'intercom',           'greenhouse'),
('Island',               'island',             'greenhouse'),
('Iterable',             'iterable',           'greenhouse'),
('Jellyfish',            'jellyfish',          'greenhouse'),
('Kandji',               'kandji',             'greenhouse'),
('Klaviyo',              'klaviyo',            'greenhouse'),
('Klarna',               'klarna',             'greenhouse'),
('Kustomer',             'kustomer',           'greenhouse'),
('LaunchDarkly',         'launchdarkly',       'greenhouse'),
('Lattice',              'lattice',            'greenhouse'),
('Lemonade',             'lemonade',           'greenhouse'),
('LiveRamp',             'liveramp',           'greenhouse'),
('Lob',                  'lob',                'greenhouse'),
('LogRocket',            'logrocket',          'greenhouse'),
('Loom',                 'loom',               'greenhouse'),
('Lunchbox',             'lunchbox',           'greenhouse'),
('Lyra Health',          'lyrahealth',         'greenhouse'),
('Malwarebytes',         'malwarebytes',       'greenhouse'),
('Marqeta',              'marqeta',            'greenhouse'),
('MasterClass',          'masterclass',        'greenhouse'),
('Matterport',           'matterport',         'greenhouse'),
('Maze',                 'maze',               'greenhouse'),
('Merge',                'merge',              'greenhouse'),
('Metabase',             'metabase',           'greenhouse'),
('MessageBird',          'messagebird',        'greenhouse'),
('Miro',                 'miro',               'greenhouse'),
('Mixpanel',             'mixpanel',           'greenhouse'),
('Modern Health',        'modernhealth',       'greenhouse'),
('MongoDB',              'mongodb',            'greenhouse'),
('Moveworks',            'moveworks',          'greenhouse'),
('Mozilla',              'mozilla',            'greenhouse'),
('MX Technologies',      'mx',                 'greenhouse'),
('Narvar',               'narvar',             'greenhouse'),
('Netlify',              'netlify',            'greenhouse'),
('Nexthink',             'nexthink',           'greenhouse'),
('Nextdoor',             'nextdoor',           'greenhouse'),
('Noom',                 'noom',               'greenhouse'),
('Notion',               'notion',             'greenhouse'),
('Nova Credit',          'novacredit',         'greenhouse'),
('Numerator',            'numerator',          'greenhouse'),
('Okta',                 'okta',               'greenhouse'),
('Omada Health',         'omadahealth',        'greenhouse'),
('OneTrust',             'onetrust',           'greenhouse'),
('OpenAI',               'openai',             'greenhouse'),
('Opendoor',             'opendoor',           'greenhouse'),
('Orca Security',        'orcasecurity',       'greenhouse'),
('Outreach',             'outreach',           'greenhouse'),
('PagerDuty',            'pagerduty',          'greenhouse'),
('Patreon',              'patreon',            'greenhouse'),
('People.ai',            'peopleai',           'greenhouse'),
('Persona',              'persona',            'greenhouse'),
('Pie Insurance',        'pieinsurance',       'greenhouse'),
('Plaid',                'plaid',              'greenhouse'),
('Planet Labs',          'planet',             'greenhouse'),
('Policygenius',         'policygenius',       'greenhouse'),
('Postman',              'postman',            'greenhouse'),
('Procore',              'procore',            'greenhouse'),
('Productboard',         'productboard',       'greenhouse'),
('Pulumi',               'pulumi',             'greenhouse'),
('Qualia',               'qualia',             'greenhouse'),
('Qualified',            'qualified',          'greenhouse'),
('Quizlet',              'quizlet',            'greenhouse'),
('Ramp',                 'ramp',               'greenhouse'),
('Razorpay',             'razorpay',           'greenhouse'),
('Recurly',              'recurly',            'greenhouse'),
('Reddit',               'reddit',             'greenhouse'),
('Relativity',           'relativity',         'greenhouse'),
('Replit',               'replit',             'greenhouse'),
('Riskified',            'riskified',          'greenhouse'),
('Robinhood',            'robinhood',          'greenhouse'),
('Rockset',              'rockset',            'greenhouse'),
('Samsara',              'samsara',            'greenhouse'),
('Sardine',              'sardine',            'greenhouse'),
('Scale AI',             'scaleai',            'greenhouse'),
('Scribd',               'scribd',             'greenhouse'),
('Segment',              'segment',            'greenhouse'),
('Seismic',              'seismic',            'greenhouse'),
('Sentry',               'sentry',             'greenhouse'),
('Shield AI',            'shieldai',           'greenhouse'),
('Sigma Computing',      'sigmacomputing',     'greenhouse'),
('Sisense',              'sisense',            'greenhouse'),
('Skillz',               'skillz',             'greenhouse'),
('Snyk',                 'snyk',               'greenhouse'),
('SonarSource',          'sonarsource',        'greenhouse'),
('SoundHound',           'soundhoundinc',      'greenhouse'),
('SpotOn',               'spoton',             'greenhouse'),
('Spring Health',        'springhealth',       'greenhouse'),
('StockX',               'stockx',             'greenhouse'),
('Stripe',               'stripe',             'greenhouse'),
('Substack',             'substack',           'greenhouse'),
('Superhuman',           'superhuman',         'greenhouse'),
('Swimlane',             'swimlane',           'greenhouse'),
('Tanium',               'tanium',             'greenhouse'),
('Temporal',             'temporaltech',       'greenhouse'),
('Terminus',             'terminus',           'greenhouse'),
('Thoughtspot',          'thoughtspot',        'greenhouse'),
('Toast',                'toast',              'greenhouse'),
('TrueLayer',            'truelayer',          'greenhouse'),
('Twilio',               'twilio',             'greenhouse'),
('Typeform',             'typeform',           'greenhouse'),
('Udemy',                'udemy',              'greenhouse'),
('Upwork',               'upwork',             'greenhouse'),
('Uptycs',               'uptycs',             'greenhouse'),
('Vanta',                'vanta',              'greenhouse'),
('Vercel',               'vercelcareer',       'greenhouse'),
('Verkada',              'verkada',            'greenhouse'),
('Vidyard',              'vidyard',            'greenhouse'),
('Visier',               'visier',             'greenhouse'),
('Webflow',              'webflow',            'greenhouse'),
('Weights & Biases',     'wandb',              'greenhouse'),
('Whatnot',              'whatnot',            'greenhouse'),
('Wonolo',               'wonolo',             'greenhouse'),
('Workato',              'workato',            'greenhouse'),
('Workiva',              'workiva',            'greenhouse'),
('WorkOS',               'workos',             'greenhouse'),
('Writer',               'writer',             'greenhouse'),
('Yotpo',                'yotpo',              'greenhouse'),
('Zendesk',              'zendesk',            'greenhouse'),
('Zeta Global',          'zetaglobal',         'greenhouse'),
('Zscaler',              'zscaler',            'greenhouse'),
('Zuora',                'zuora',              'greenhouse'),

-- ─────────────────────────────────────────────────────────────────────────────
-- ASHBY  (jobs.ashbyhq.com/{slug})
-- ─────────────────────────────────────────────────────────────────────────────

('Attio',                'attio',              'ashby'),
('Beehiiv',              'beehiiv',            'ashby'),
('Browserbase',          'browserbase',        'ashby'),
('Cal.com',              'cal',                'ashby'),
('Clerk',                'clerk',              'ashby'),
('Cursor',               'anysphere',          'ashby'),
('Descript',             'descript',           'ashby'),
('Drata',                'drata',              'ashby'),
('Fleet',                'fleetdm',            'ashby'),
('Hex',                  'hex',                'ashby'),
('Inngest',              'inngest',            'ashby'),
('Linear',               'linear',             'ashby'),
('Liveblocks',           'liveblocks',         'ashby'),
('Mercury',              'mercury',            'ashby'),
('Mintlify',             'mintlify',           'ashby'),
('Modal',                'modal',              'ashby'),
('Neon',                 'neon',               'ashby'),
('Perplexity',           'perplexity',         'ashby'),
('PostHog',              'posthog',            'ashby'),
('Railway',              'railway',            'ashby'),
('Render',               'render',             'ashby'),
('Resend',               'resend',             'ashby'),
('Retool',               'retool',             'ashby'),
('Secoda',               'secoda',             'ashby'),
('Supabase',             'supabase',           'ashby'),
('Trigger.dev',          'trigger',            'ashby'),
('Turso',                'turso',              'ashby'),
('Vapi',                 'vapi',               'ashby'),
('Warp',                 'warp',               'ashby'),
('37signals',            '37signals',          'ashby'),

-- ─────────────────────────────────────────────────────────────────────────────
-- LEVER  (jobs.lever.co/{slug})
-- ─────────────────────────────────────────────────────────────────────────────

('10x Genomics',         '10xgenomics',        'lever'),
('Calm',                 'calm',               'lever'),
('Checkout.com',         'checkout',           'lever'),
('DraftKings',           'draftkings',         'lever'),
('Faire',                'faire',              'lever'),
('Gem',                  'gem',                'lever'),
('Grindr',               'grindr',             'lever'),
('Headway',              'headway',            'lever'),
('Ironclad',             'ironclad',           'lever'),
('JumpCloud',            'jumpcloud',          'lever'),
('Lyft',                 'lyft',               'lever'),
('Niantic',              'niantic',            'lever'),
('OpenPhone',            'openphone',          'lever'),
('Palantir',             'palantir',           'lever'),
('Pilot',                'pilot',              'lever'),
('Rippling',             'rippling',           'lever'),
('ShipBob',              'shipbob',            'lever'),
('SurveyMonkey',         'surveymonkey',       'lever'),
('Udacity',              'udacity',            'lever'),
('Waymo',                'waymo',              'lever'),
('Wealthfront',          'wealthfront',        'lever')

ON CONFLICT (ats, slug) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────
-- ADDITIONAL ENTRIES — expanding to ~500 verified companies
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO company_directory (name, slug, ats) VALUES

-- Additional Greenhouse companies
('AlphaSense',           'alphasense',         'greenhouse'),
('Anaplan',              'anaplan',            'greenhouse'),
('Andela',               'andela',             'greenhouse'),
('AppFolio',             'appfolio',           'greenhouse'),
('Arize AI',             'arizeai',            'greenhouse'),
('Atlan',                'atlan',              'greenhouse'),
('Axios',                'axios',              'greenhouse'),
('Bluecore',             'bluecore',           'greenhouse'),
('Bluevine',             'bluevine',           'greenhouse'),
('Buildkite',            'buildkite',          'greenhouse'),
('CallRail',             'callrail',           'greenhouse'),
('Cato Networks',        'catonetworks',       'greenhouse'),
('Chainalysis',          'chainalysis',        'greenhouse'),
('Chronosphere',         'chronosphere',       'greenhouse'),
('Clipboard Health',     'clipboardhealth',    'greenhouse'),
('Cohere',               'cohere',             'greenhouse'),
('Color Health',         'color',              'greenhouse'),
('Crunchbase',           'crunchbase',         'greenhouse'),
('DigitalOcean',         'digitalocean',       'greenhouse'),
('Discord',              'discord',            'greenhouse'),
('Domo',                 'domo',               'greenhouse'),
('Eppo',                 'eppo',               'greenhouse'),
('Evolent Health',       'evolenthealth',      'greenhouse'),
('Expel',                'expel',              'greenhouse'),
('FactSet',              'factset',            'greenhouse'),
('Fountain',             'fountain',           'greenhouse'),
('Gainsight',            'gainsight',          'greenhouse'),
('Handshake',            'joinhandshake',      'greenhouse'),
('Headspace',            'headspace',          'greenhouse'),
('Homebase',             'joinhomebase',       'greenhouse'),
('Hunters',              'huntersinc',         'greenhouse'),
('Incredible Health',    'incrediblehealth',   'greenhouse'),
('Later',                'later',              'greenhouse'),
('LogicMonitor',         'logicmonitor',       'greenhouse'),
('Lookout',              'lookout',            'greenhouse'),
('Lucidchart',           'lucid',              'greenhouse'),
('Mattermost',           'mattermost',         'greenhouse'),
('Mend',                 'mend',               'greenhouse'),
('Mimecast',             'mimecast',           'greenhouse'),
('NAVAN',                'navan',              'greenhouse'),
('Nylas',                'nylas',              'greenhouse'),
('Observe',              'observeinc',         'greenhouse'),
('Ontra',                'ontra',              'greenhouse'),
('OpenGov',              'opengov',            'greenhouse'),
('Payscale',             'payscale',           'greenhouse'),
('Pendo',                'pendo',              'greenhouse'),
('Podium',               'podium',             'greenhouse'),
('Prefect',              'prefect',            'greenhouse'),
('Rapid7',               'rapid7',             'greenhouse'),
('Red Canary',           'redcanary',          'greenhouse'),
('Remote',               'remote',             'greenhouse'),
('Rootly',               'rootly',             'greenhouse'),
('SailPoint',            'sailpoint',          'greenhouse'),
('Salesloft',            'salesloft',          'greenhouse'),
('Sauce Labs',           'saucelabs',          'greenhouse'),
('SecurityScorecard',    'securityscorecard',  'greenhouse'),
('SentinelOne',          'sentinelone',        'greenhouse'),
('Signifyd',             'signifyd',           'greenhouse'),
('Smartly',              'smartly',            'greenhouse'),
('Socure',               'socure',             'greenhouse'),
('SolarWinds',           'solarwinds',         'greenhouse'),
('Sprinklr',             'sprinklr',           'greenhouse'),
('Sprout Social',        'sproutsocial',       'greenhouse'),
('Sysdig',               'sysdig',             'greenhouse'),
('Tailscale',            'tailscale',          'greenhouse'),
('Talkdesk',             'talkdesk',           'greenhouse'),
('Tessian',              'tessian',            'greenhouse'),
('Traceable',            'traceableai',        'greenhouse'),
('Transcarent',          'transcarent',        'greenhouse'),
('Trustpilot',           'trustpilot',         'greenhouse'),
('Unqork',               'unqork',             'greenhouse'),
('UserTesting',          'usertesting',        'greenhouse'),
('Valon',                'valon',              'greenhouse'),
('Vivun',                'vivun',              'greenhouse'),
('Vouch',                'vouchforit',         'greenhouse'),
('WalkMe',               'walkme',             'greenhouse'),
('Walnut',               'walnut',             'greenhouse'),
('Weaviate',             'weaviate',           'greenhouse'),
('Windfall',             'windfall',           'greenhouse'),
('Xactly',               'xactly',             'greenhouse'),
('Yext',                 'yext',               'greenhouse'),
('Yubico',               'yubico',             'greenhouse'),
('Zerto',                'zerto',              'greenhouse'),
('Zoominfo',             'zoominfo',           'greenhouse'),
('Speechify',            'speechify',          'greenhouse'),
('Airbase',              'airbase',            'greenhouse'),
('AuditBoard',           'auditboard',         'greenhouse'),
('DevRev',               'devrev',             'greenhouse'),
('dLocal',               'dlocal',             'greenhouse'),
('Eightfold AI',         'eightfold',          'greenhouse'),
('Egnyte',               'egnyte',             'greenhouse'),
('ExtraHop',             'extrahop',           'greenhouse'),
('Filevine',             'filevine',           'greenhouse'),
('Flatiron Health',      'flatironhealth',     'greenhouse'),
('FloQast',              'floqast',            'greenhouse'),
('Flywire',              'flywire',            'greenhouse'),
('Movable Ink',          'movableink',         'greenhouse'),
('Mural',                'mural',              'greenhouse'),
('Nerdio',               'nerdio',             'greenhouse'),
('Sumo Logic',           'sumologic',          'greenhouse'),
('Pave',                 'pave',               'greenhouse'),
('Rollbar',              'rollbar',            'greenhouse'),
('Shippo',               'shippo',             'greenhouse'),
('Saviynt',              'saviynt',            'greenhouse'),
('SnapLogic',            'snaplogic',          'greenhouse'),
('FreshBooks',           'freshbooks',         'greenhouse'),
('Rho',                  'rho',                'greenhouse'),
('Parabola',             'parabola',           'greenhouse'),
('Quantive',             'quantive',           'greenhouse'),
('Brightside Health',    'brightside',         'greenhouse'),
('Monte Carlo',          'montecarlodata',     'greenhouse'),
('Mode Analytics',       'mode',               'greenhouse'),
('Immuta',               'immuta',             'greenhouse'),
('Privy',                'privy',              'greenhouse'),
('Censys',               'censys',             'greenhouse'),
('Lacework',             'lacework',           'greenhouse'),
('Silverfort',           'silverfort',         'greenhouse'),
('Deepwatch',            'deepwatch',          'greenhouse'),
('Jungle Scout',         'junglescout',        'greenhouse'),
('Kevel',                'kevel',              'greenhouse'),
('Mine',                 'minehq',             'greenhouse'),
('Nooks',                'nooks',              'greenhouse'),
('Maxio',                'maxio',              'greenhouse'),
('MNTN',                 'mntn',               'greenhouse'),
('Cerby',                'cerby',              'greenhouse'),
('Locus',                'locus',              'greenhouse'),
('Mediafly',             'mediafly',           'greenhouse'),
('Cybereason',           'cybereason',         'greenhouse'),
('Obsidian Security',    'obsidian',           'greenhouse'),
('Relay Payments',       'relaypayments',      'greenhouse'),
('Rupa Health',          'rupahealth',         'greenhouse'),
('Noname Security',      'nonamesecurity',     'greenhouse'),
('Protect AI',           'protectai',          'greenhouse'),
('Torq',                 'torq',               'greenhouse'),
('Relyance AI',          'relyanceai',         'greenhouse'),
('Salsify',              'salsify',            'greenhouse'),
('Ridgeline',            'ridgeline',          'greenhouse'),
('Skylo',                'skylo',              'greenhouse'),
('Reachdesk',            'reachdesk',          'greenhouse'),

-- Additional Ashby companies
('Anrok',                'anrok',              'ashby'),
('Cognition AI',         'cognition-labs',     'ashby'),
('Common Room',          'commonroom',         'ashby'),
('Coactive AI',          'coactive',           'ashby'),
('Dagster Labs',         'dagster',            'ashby'),
('Dust',                 'dust-tt',            'ashby'),
('Elicit',               'elicit',             'ashby'),
('EvenUp',               'evenup',             'ashby'),
('Fieldguide',           'fieldguide',         'ashby'),
('Fireworks AI',         'fireworks-ai',       'ashby'),
('Gamma',                'gamma',              'ashby'),
('Harvey',               'harvey',             'ashby'),
('Lago',                 'getlago',            'ashby'),
('Lovable',              'lovable',            'ashby'),
('Orb',                  'withorb',            'ashby'),
('Oyster HR',            'oysterhr',           'ashby'),
('Paragon',              'useparagon',         'ashby'),
('Permit.io',            'permit',             'ashby'),
('Pika Labs',            'pika',               'ashby'),
('Plane',                'makeplane',          'ashby'),
('Polar',                'polar',              'ashby'),
('Replicate',            'replicate',          'ashby'),
('Sequin',               'sequin',             'ashby'),
('Settle',               'settle',             'ashby'),
('Speakeasy',            'speakeasy-api',      'ashby'),
('Stainless',            'stainless-api',      'ashby'),
('Stedi',                'stedi',              'ashby'),
('Tempo Labs',           'tempolabs',          'ashby'),
('Upstash',              'upstash',            'ashby'),
('Watershed',            'watershed',          'ashby'),

-- Additional Lever companies
('Benchsci',             'benchsci',           'lever'),
('Clio',                 'clio',               'lever'),
('Coveo',                'coveo',              'lever'),
('Housecall Pro',        'housecallpro',       'lever'),
('Impartner',            'impartner',          'lever'),
('Kraken',               'krakenfx',           'lever'),
('LeafLink',             'leaflink',           'lever'),
('OpenX',                'openx',              'lever'),
('Personio',             'personio',           'lever'),
('Phreesia',             'phreesia',           'lever'),
('Proofpoint',           'proofpoint',         'lever'),
('Rokt',                 'rokt',               'lever'),
('Smartsheet',           'smartsheet',         'lever'),
('Teikametrics',         'teikametrics',       'lever'),
('ThoughtWorks',         'thoughtworks',       'lever'),
('Via',                  'ridewithvia',        'lever'),
('WP Engine',            'wpengine',           'lever'),
('Yieldstreet',          'yieldstreet',        'lever'),

-- More Lever companies
('Angi',                 'angihomeservices',   'lever'),
('Cityblock Health',     'cityblock',          'lever'),
('Coalition',            'thecoalition',       'lever'),
('Compass',              'compass',            'lever'),
('Convoy',               'convoy',             'lever'),
('DailyPay',             'dailypay',           'lever'),
('Devoted Health',       'devoted',            'lever'),
('Forward',              'goforward',          'lever'),
('GoodLeap',             'goodleap',           'lever'),
('Hippo Insurance',      'hippo',              'lever'),
('Honor',                'honorhome',          'lever'),
('Hopin',                'hopin',              'lever'),
('ID.me',                'idme',               'lever'),
('Inovalon',             'inovalon',           'lever'),
('Jerry',                'getjerry',           'lever'),
('Jobber',               'jobber',             'lever'),
('LegalZoom',            'legalzoom',          'lever'),
('Liftoff',              'liftoff',            'lever'),
('Loop Returns',         'loopreturns',        'lever'),
('Model N',              'modeln',             'lever'),
('Mosaic',               'mosaictech',         'lever'),
('NEXT Insurance',       'nextinsurance',      'lever'),
('Newfront Insurance',   'newfront',           'lever'),
('Onapsis',              'onapsis',            'lever'),
('Oscar Health',         'oscar',              'lever'),
('Ping Identity',        'pingidentity',       'lever'),
('PsiQuantum',           'psiquantum',         'lever'),
('Recharge',             'rechargepayments',   'lever'),
('Remitly',              'remitly',            'lever'),
('Rocket Lawyer',        'rocketlawyer',       'lever'),
('Seatgeek',             'seatgeek',           'lever'),
('Sendbird',             'sendbird',           'lever'),
('Slice',                'slicelife',          'lever'),
('Stash',                'stash',              'lever'),
('Sword Health',         'swordhealth',        'lever'),
('Syndio',               'syndio',             'lever'),
('Teachable',            'teachable',          'lever'),
('TextNow',              'textnow',            'lever'),
('Thumbtack',            'thumbtack',          'lever'),
('TrueAccord',           'trueaccord',         'lever'),
('Upside',               'upside',             'lever'),
('Vendr',                'vendr',              'lever'),
('WEX',                  'wexinc',             'lever'),
('Xometry',              'xometry',            'lever'),
('Zipline',              'flyzipline',         'lever'),
('Knotch',               'knotch',             'lever'),
('Salary.com',           'salary',             'lever'),
('Middesk',              'middesk',            'lever'),
('Bettercloud',          'bettercloud',        'lever'),
('ClassDojo',            'classdojo',          'lever'),
('Clearco',              'clear',              'lever'),
('Current',              'current',            'lever'),
('Everbridge',           'everbridge',         'lever'),
('Flexe',                'flexe',              'lever'),
('Hippo',                'hippoeducation',     'lever'),
('Housecall Pro',        'hcp',                'lever'),

-- More Ashby companies
('Baseten',              'baseten',            'ashby'),
('Axiom',                'axiom',              'ashby'),
('Cast AI',              'cast-ai',            'ashby'),
('Descope',              'descope',            'ashby'),
('Dune Analytics',       'dune',               'ashby'),
('Embroker',             'embroker',           'ashby'),
('Estuary',              'estuary',            'ashby'),
('Faros AI',             'farosai',            'ashby'),
('Float',                'float',              'ashby'),
('Folk',                 'folk',               'ashby'),
('Framer',               'framer',             'ashby'),
('Freshpaint',           'freshpaint',         'ashby'),
('Frontegg',             'frontegg',           'ashby'),
('Gorgias',              'gorgias',            'ashby'),
('Graphite',             'graphite',           'ashby'),
('Growthbook',           'growthbook',         'ashby'),
('Hatica',               'hatica',             'ashby'),
('Hookdeck',             'hookdeck',           'ashby'),
('Human Signal',         'humansignal',        'ashby'),
('Incident.io',          'incident',           'ashby'),
('Infisical',            'infisical',          'ashby'),
('Iterative',            'iterative',          'ashby'),
('Knock',                'knock',              'ashby'),
('Laika',                'heylaika',           'ashby'),
('Lakera',               'lakera',             'ashby'),
('Langfuse',             'langfuse',           'ashby'),
('Lightdash',            'lightdash',          'ashby'),
('Lightspark',           'lightspark',         'ashby'),
('Lithic',               'lithic',             'ashby'),
('Livekit',              'livekit',            'ashby'),
('Lumos',                'asklumos',           'ashby'),
('Mage AI',              'mage-ai',            'ashby'),
('Metaplane',            'metaplane',          'ashby'),
('Metronome',            'metronome',          'ashby'),
('Novu',                 'novu',               'ashby'),
('Omni',                 'omnianalytics',      'ashby'),
('Openbb',               'openbb',             'ashby'),
('Outerbounds',          'outerbounds',        'ashby'),
('Oura',                 'oura',               'ashby'),
('Lexion',               'lexion',             'ashby'),
('Dragonfly DB',         'dragonflydb',        'ashby'),
('Dub',                  'dub',                'ashby'),
('Evervault',            'evervault',          'ashby'),
('Extend',               'paywithextend',      'ashby'),
('Copper',               'copper',             'ashby'),
('Cortex',               'cortex',             'ashby'),
('Courier',              'trycourier',         'ashby'),
('Lusha',                'lusha',              'ashby'),
('Kinde',                'kinde',              'ashby')

ON CONFLICT (ats, slug) DO NOTHING;
